#!/bin/bash
# Automatic Authentication Setup Script
# Configures all authentication types (OAuth/JWT, Basic Auth, mTLS) with generated tokens

set -e

BASE_URL="${BASE_URL:-http://localhost:5000}"
CONFIG_FILE="auth.config"

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║     SCIM Authentication Setup - All Types Enabled            ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# Check if server is running
echo "Checking if server is running at $BASE_URL..."
if ! curl -s -f "$BASE_URL" > /dev/null 2>&1; then
    echo "❌ Error: Server is not running at $BASE_URL"
    echo ""
    echo "Please start the server first:"
    echo "  python3 app.py"
    echo ""
    echo "Then run this script again."
    exit 1
fi
echo "✓ Server is running"
echo ""

# Fetch tokens
echo "Fetching authentication tokens from $BASE_URL/api/dev/tokens..."
RESPONSE=$(curl -s "$BASE_URL/api/dev/tokens")

if [ $? -ne 0 ]; then
    echo "❌ Failed to fetch tokens"
    exit 1
fi
echo "✓ Tokens fetched successfully"
echo ""

# Check if jq is available
if ! command -v jq &> /dev/null; then
    echo "❌ Error: jq is required but not installed"
    echo "Install it with: brew install jq (macOS) or apt-get install jq (Linux)"
    exit 1
fi

# Extract configuration values
PUBLIC_KEY=$(echo "$RESPONSE" | jq -r '.keys.public_key')
ADMIN_HASH=$(echo "$RESPONSE" | jq -r '.tokens.basic_auth.admin.password_hash')
TESTUSER_HASH=$(echo "$RESPONSE" | jq -r '.tokens.basic_auth.testuser.password_hash')
READONLY_HASH=$(echo "$RESPONSE" | jq -r '.tokens.basic_auth.readonly.password_hash')

# Create configuration file
echo "Creating authentication configuration file: $CONFIG_FILE"
cat > "$CONFIG_FILE" << EOF
# Authentication Configuration - All Types Enabled
# Generated by setup_auth.sh on $(date)

# ============================================================================
# OAUTH 2.0 / JWT CONFIGURATION (ENABLED)
# ============================================================================
export AUTH_OAUTH_ENABLED=true
export AUTH_JWT_ENABLED=true
export AUTH_JWT_ISSUER=https://test-idp.example.com
export AUTH_JWT_AUDIENCE=scim-service-provider
export AUTH_JWT_ALGORITHM=RS256

# JWT Public Key (auto-generated)
export AUTH_JWT_PUBLIC_KEY='$PUBLIC_KEY'

# ============================================================================
# BASIC AUTHENTICATION CONFIGURATION (ENABLED)
# ============================================================================
export AUTH_BASIC_ENABLED=true

# Users: admin:admin123, testuser:testpass123, readonly:readonly123
export AUTH_BASIC_USERS='admin:$ADMIN_HASH,testuser:$TESTUSER_HASH,readonly:$READONLY_HASH'

# ============================================================================
# MUTUAL TLS CONFIGURATION (ENABLED)
# ============================================================================
export AUTH_MTLS_ENABLED=true
export AUTH_MTLS_REQUIRE_CERT=false

# ============================================================================
# AUTHORIZATION CONFIGURATION
# ============================================================================
export AUTH_ENFORCE_AUTHZ=true
EOF

echo "✓ Configuration file created: $CONFIG_FILE"
echo ""

# Show summary
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                    Setup Complete!                            ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "All authentication types are now configured:"
echo "  ✓ OAuth 2.0 / JWT (Bearer Token)"
echo "  ✓ HTTP Basic Authentication"
echo "  ✓ Mutual TLS (mTLS)"
echo ""
echo "To use this configuration:"
echo ""
echo "  1. Load the configuration:"
echo "     source $CONFIG_FILE"
echo ""
echo "  2. Restart the server:"
echo "     python3 app.py"
echo ""
echo "  3. Test with any authentication method:"
echo ""
echo "     # JWT Token"
echo "     TOKEN=\$(curl -s $BASE_URL/api/dev/tokens | jq -r '.tokens.jwt.full_access.token')"
echo "     curl -H \"Authorization: Bearer \$TOKEN\" $BASE_URL/scim/v2/Users"
echo ""
echo "     # Basic Auth"
echo "     curl -u admin:admin123 $BASE_URL/scim/v2/Users"
echo ""
echo "     # Or use the helper script"
echo "     ./get_tokens.sh"
echo ""
echo "Available credentials:"
echo "  - admin / admin123 (full access)"
echo "  - testuser / testpass123 (standard user)"
echo "  - readonly / readonly123 (read-only)"
echo ""
echo "For IAM system integration, use any of these authentication methods."
echo "See TOKEN_GENERATION_GUIDE.md for detailed documentation."
echo ""

# Made with Bob
